spring:
  profiles:
    # 로컬: local, 배포: rds 사용
    active: ["rds", "swagger", "s3"]

  security:
    user:
      password: 1

logging:
  level:
    org:
      springframework:
        security=DEBUG:
